/**
 * UBS thematic handbooks — FLORA, FAUNA, REALIA (CC BY-SA 4.0).
 *
 * Pure parsing only. No Node imports: file reads, hashing and the doctor report
 * live in `scripts/import-ubs-flora-fauna.ts`. This file knows the *format*.
 *
 * DATA ONLY. The image archives are deliberately not fetched and never should
 * be by this codebase: Fauna.zip 391,931,013 b, Flora.zip 369,165,143 b,
 * Realia.zip 1,629,685,060 b — 2,390,781,216 b, 2.4 GB, for 746 plates. The
 * three XML files this module parses are 4,589,301 b together. What we import
 * is the *metadata* for every plate (id, filename, collection, copyright,
 * caption) so a card can name and credit a picture it does not ship.
 *
 * ── Three things a later reader must not "fix" ─────────────────────────────
 *
 * 1. DO NOT KEY ON `<Path>`. See `UBS_FFR_PATH_IS_UNUSABLE`. There is exactly
 *    one distinct Path value in all three files — `marble-images-flora-fauna
 *    -realia\FAUNA` — and it is emitted for FLORA's images too. It is wrong
 *    for 202 of the 362 elements that carry it (56%), absent from all 392
 *    REALIA images, and it uses Windows backslashes. `FileName` + `Collection`
 *    are the real coordinates. This module does not expose Path as a path.
 *
 * 2. THE NESTING IS NOT WHAT IT LOOKS LIKE. `LanguageSets` and `BibleImages`
 *    are children of `Sections/Section`, *not* of `ThemLex_Entry` — except in
 *    REALIA, where one entry also carries a `BibleImages` directly on the
 *    entry (2 images). A parser that walks `ThemLex_Entry > LanguageSets`
 *    finds zero of the 22,244 references and reports success. Hence
 *    `UBS_FFR_MIN_COUNTS` and the floors asserted in the importer: a count
 *    that comes back zero here is a parser bug, not an empty source.
 *
 * 3. COPYRIGHT IS PER IMAGE. 380 distinct copyright strings across 754 plates.
 *    "© United Bible Societies" as a blanket credit would be false attribution
 *    for the great majority of them — they are Wikimedia Commons contributors,
 *    Pixabay, museums, and 80 images generated by OpenAI models. Several
 *    strings carry their own CC licence rider (CC BY-SA 3.0, CC0, CC BY 2.0),
 *    which is narrower or wider than the handbook's own CC BY-SA 4.0. Never
 *    collapse these; `parseImageCopyright` keeps the raw string verbatim and
 *    only *adds* structure alongside it.
 */

import { BOOK_CODES, type BookCode } from "../reference/types.js";

/** The three handbooks, by the collection name used in their file names. */
export const UBS_FFR_HANDBOOKS = ["FLORA", "FAUNA", "REALIA"] as const;

export type UbsFfrHandbook = (typeof UBS_FFR_HANDBOOKS)[number];

/** SPDX identifier. All three handbooks, and their READMEs, say the same. */
export const UBS_FFR_LICENSE = "CC-BY-SA-4.0";

export const UBS_FFR_LICENSE_URL = "http://creativecommons.org/licenses/by-sa/4.0/";

/**
 * Attribution strings, verbatim from `flora-fauna-realia/README.md`, including
 * its own double spaces after "2025." in the flora and realia lines. Each
 * handbook is a two-step chain — UBS 2025 adaptation of a named 2005/2009/2012
 * monograph — and both halves are required. Reproduce whole.
 */
export const UBS_FFR_ATTRIBUTION: Readonly<Record<UbsFfrHandbook, string>> = {
  FAUNA:
    "Animals in the Bible © United Bible Societies, 2025. Adapted from: All Creatures Great and Small: Living Things in the Bible, by Edward R. Hope © 2005 United Bible Societies.",
  FLORA:
    "Plants and Trees in the Bible © United Bible Societies, 2025.  Adapted from: Each According to its Kind: Plants and Trees in the Bible, by Robert Koops © 2012 United Bible Societies.",
  REALIA:
    "Human-made Things in the Bible © United Bible Societies, 2025.  Adapted from: The Works of Their Hands: Man-made Things in the Bible, by Ray Pritz © 2009 United Bible Societies.",
};

/** The human title of each handbook, as its README heading gives it. */
export const UBS_FFR_TITLES: Readonly<Record<UbsFfrHandbook, string>> = {
  FLORA: "Plants and Trees in the Bible (Flora Handbook)",
  FAUNA: "Animals in the Bible (Fauna Handbook)",
  REALIA: "Human-made Things in the Bible (Realia Handbook)",
};

/**
 * Licence riders that survive the blanket "CC BY-SA 4.0" on the tin. These are
 * not editorial commentary; each one changes what a compliant build may do.
 */
export const UBS_FFR_LICENSE_RIDERS: readonly string[] = [
  "ShareAlike: CC BY-SA 4.0 §3(b) makes any index derived from these files Adapted Material, which must itself be CC BY-SA 4.0 or a Compatible Licence. Keep UBS-derived fields in their own artefact — do not co-mingle them into a file that also carries fields from a BY-NC source, because BY-SA and BY-NC cannot both govern one adaptation.",
  "Per-image copyright: the handbook licence covers the UBS *text*. Each plate carries its own Copyright string and, frequently, its own CC licence (CC0, CC BY 2.0, CC BY-SA 3.0, CC BY-SA 4.0, 'Public domain', 'Source unknown'). 380 distinct strings across 754 plates. Crediting only UBS would be false attribution.",
  "The authoritative per-image detail is in `flora-fauna-realia/flora images-copyright.pdf` (102,566 b) and `fauna images-copyright.pdf` (103,862 b). There is NO equivalent PDF for REALIA, whose 392 plates are the largest group and are documented only by the in-XML Copyright element.",
  "Image bytes are not licensed by these XML files and are not fetched. Shipping a plate requires clearing that plate's own Copyright string, not the handbook's.",
  "8 plates carry an empty Copyright element and 6 more say only 'Source unknown' / '(Source unknown)'. These are not attributable and must not be displayed.",
  "80 plates are machine-generated ('Image generated by ChatGPT using OpenAI technology', Collection OPEN-AI). Authorship and licence of model output are unsettled in several jurisdictions; treat them as neither UBS-authored nor public domain.",
];

/**
 * The image archives, recorded so nobody has to discover their size the hard
 * way. These are facts to cite, not URLs to fetch.
 */
export const UBS_FFR_IMAGE_ARCHIVES: Readonly<
  Record<UbsFfrHandbook, { readonly url: string; readonly bytes: number }>
> = {
  FAUNA: { url: "https://d22edu6iq8vokk.cloudfront.net/collections/Fauna.zip", bytes: 391_931_013 },
  FLORA: { url: "https://d22edu6iq8vokk.cloudfront.net/collections/Flora.zip", bytes: 369_165_143 },
  REALIA: { url: "https://d22edu6iq8vokk.cloudfront.net/collections/Realia.zip", bytes: 1_629_685_060 },
};

/** Total bytes of image archive deliberately NOT downloaded. */
export const UBS_FFR_IMAGE_ARCHIVE_TOTAL_BYTES = 2_390_781_216;

/**
 * The single `<Path>` value present in the corpus, kept only so a test can
 * assert we still refuse to use it. It is a constant, it names FAUNA inside
 * FLORA, and it is Windows-shaped. See note 1 in the file header.
 */
export const UBS_FFR_PATH_IS_UNUSABLE = "marble-images-flora-fauna-realia\\FAUNA" as const;

/**
 * Floors, measured on the v1.1 EN files. Asserted by the importer so that a
 * silent parse failure cannot pass as a clean run (a check that finds nothing
 * must prove it looked in the right place).
 */
export const UBS_FFR_MIN_COUNTS: Readonly<
  Record<UbsFfrHandbook, { entries: number; languageSets: number; references: number; images: number }>
> = {
  FLORA: { entries: 141, languageSets: 283, references: 1_924, images: 202 },
  FAUNA: { entries: 114, languageSets: 303, references: 3_583, images: 160 },
  REALIA: { entries: 507, languageSets: 1_619, references: 16_737, images: 392 },
};

// ───────────────────────────── MARBLE references ─────────────────────────────

/**
 * The corpus sigil that may prefix a reference. It marks *which text* the
 * reference indexes, and it is NOT the same thing as the entry's
 * `LanguageSet Language`: 1,704 references sit in a Greek language set but
 * carry `L`, and 20 sit in a Hebrew set carrying `A`. FLORA and FAUNA omit the
 * sigil entirely (all 5,507 of their references are bare); only REALIA writes
 * it. Absent means "the text implied by the book number".
 *
 * The mapping below is inferred from distribution, and two of the four
 * inferences are load-bearing enough to state the evidence:
 *   L — 1,704 refs, every one in books 67+ (deuterocanon). Septuagint.
 *   V — 108 refs, every one in book 82, and book 82 is the *only* book any
 *       Latin language set points at. 2 Esdras survives in Latin, not Greek,
 *       which is why the Latin sets and the V sigil coincide there. Vulgate.
 */
export const UBS_FFR_CORPUS_SIGILS = {
  H: "masoretic-hebrew",
  A: "biblical-aramaic",
  G: "greek-new-testament",
  L: "septuagint",
  V: "vulgate-latin",
} as const;

export type UbsFfrCorpus = (typeof UBS_FFR_CORPUS_SIGILS)[keyof typeof UBS_FFR_CORPUS_SIGILS];

/**
 * MARBLE book numbers beyond the 66-book canon. Contiguous with it: MARBLE
 * numbers books 1..66 with no gap, so `MAT` is 40 (USFM's own scheme reserves
 * 40 and starts the NT at 41 — MARBLE does not). 67 onward is deuterocanon,
 * which our backbone does not carry, so these can be *named* but never
 * resolved. Identified by matching the standard USFM ordering shifted by one
 * and cross-checked against language: book 82 is Latin-only (2 Esdras).
 */
export const UBS_FFR_DEUTEROCANON_BOOKS: Readonly<Record<number, string>> = {
  67: "TOB", 68: "JDT", 69: "ESG", 70: "WIS", 71: "SIR",
  72: "BAR", 73: "LJE", 74: "S3Y", 75: "SUS", 76: "BEL",
  77: "1MA", 78: "2MA", 79: "3MA", 80: "4MA", 81: "1ES",
  82: "2ES", 83: "MAN", 84: "PS2", 85: "ODA", 86: "PSS",
};

/**
 * A decoded MARBLE reference.
 *
 * `morphemeOrdinal` is the honest name for the trailing field, and the naming
 * is the whole point — see `decodeMarbleReference` for the evidence. It is a
 * 1-based ordinal over *morphemes* (sub-word segments) within the verse, in
 * MARBLE's own segmentation. It is finer than a word index and it is not a
 * character offset.
 */
export type MarbleReference = {
  readonly raw: string;
  readonly corpus: UbsFfrCorpus | null;
  readonly bookNumber: number;
  readonly chapter: number;
  readonly verse: number;
  /** 1-based morpheme ordinal within the verse; null when the raw tail was 0. */
  readonly morphemeOrdinal: number | null;
  /**
   * The raw 5-digit tail as an integer. Kept because `morphemeOrdinal` halves
   * it and 17 of 22,244 tails are odd, so halving is lossy for those.
   */
  readonly rawTail: number;
  /** True when the tail was odd — the halving lost a half-step. */
  readonly tailWasOdd: boolean;
};

const MARBLE_RE = /^([HAGLV]?)(\d{14})$/;

/**
 * Decode one MARBLE reference: `[sigil]BBBCCCVVVTTTTT`.
 *
 * ── Fields, and how each was confirmed ─────────────────────────────────────
 *
 * BBB book, 1-based, contiguous over the 66-book canon then deuterocanon.
 *   Confirmed three independent ways, not assumed:
 *     · Hebrew language sets use exactly books 1–39, all 39 present, none
 *       outside. 1=GEN … 39=MAL. (`00700901500064` → Judges 9:15, the cedar in
 *       Jotham's parable; `01903703500014` → Psalm 37:35.)
 *     · Aramaic language sets use exactly two books, 15 and 27 — EZR and DAN
 *       under this mapping, which are precisely the two books with Aramaic
 *       portions. A one-off numbering would not land on that pair.
 *     · Latin language sets use exactly one book, 82 = 2 Esdras, the
 *       deuterocanonical book extant in Latin rather than Greek.
 *   And 258,116/258,116 SDBH Hebrew references decoded this way hit a verse
 *   that exists in oshb-wlc — zero misses.
 *
 * CCC chapter, VVV verse, both 1-based and zero-padded. No reference in the
 *   corpus has chapter 0 or verse 0, so there is no "whole book/chapter" form.
 *
 * TTTTT the trailing five digits: a *doubled 1-based morpheme ordinal* within
 *   the verse. `morphemeOrdinal = tail / 2`. The evidence, measured over the
 *   257,361 SDBH Hebrew references that carry Strong codes, scored by whether
 *   the OSHB morpheme at the predicted index has one of the entry's Strong
 *   numbers:
 *
 *     hypothesis                          in range        Strong-exact
 *     ---------------------------------   -------------   ------------
 *     morpheme ordinal = tail/2           255,717 99.4%   144,892 56.3%
 *     word position    = tail/2           182,359 70.9%    29,838 11.6%
 *     morpheme ordinal = tail/2 ± 1       257,361  100%   204,999 79.7%
 *
 *   Word-level is refuted: it falls out of range for 29% of references and is
 *   right 11.6% of the time. Morpheme-level is in range for 99.4%. It is not a
 *   character offset either — a character offset would exceed the verse's
 *   morpheme count almost always, where tail/2 stays inside it 99.4% of the
 *   time, and 22,227 of 22,244 tails are even, which a character count would
 *   have no reason to be.
 *
 *   The residual is a *drift*, not noise: exact agreement is 91% at ordinals
 *   1–4 and decays to 23% by ordinal 40+, with the error almost always
 *   positive (+1 18.1%, +2 9.2%, +3 4.6%). MARBLE therefore segments somewhat
 *   finer than OSHB and the excess accumulates through the verse. The specific
 *   extra boundary is NOT identified — the obvious candidate, OSHB's fused
 *   preposition+article segments (`Rd`, `Td`), makes agreement worse when
 *   corrected for (45.5% vs 56.3%), so it is refuted. Treat the ordinal as
 *   exact near the start of a verse and approximate deeper in.
 *
 * Returns null for anything that does not match, rather than throwing: the
 * importer counts malformed references instead of dying on one.
 */
export function decodeMarbleReference(raw: string): MarbleReference | null {
  const trimmed = raw.trim();
  const m = MARBLE_RE.exec(trimmed);
  if (!m) return null;
  const sigil = m[1] ?? "";
  const digits = m[2];
  if (digits === undefined) return null;

  const bookNumber = Number.parseInt(digits.slice(0, 3), 10);
  const chapter = Number.parseInt(digits.slice(3, 6), 10);
  const verse = Number.parseInt(digits.slice(6, 9), 10);
  const rawTail = Number.parseInt(digits.slice(9, 14), 10);

  const corpus =
    sigil === "" ? null : (UBS_FFR_CORPUS_SIGILS[sigil as keyof typeof UBS_FFR_CORPUS_SIGILS] ?? null);

  return {
    raw: trimmed,
    corpus,
    bookNumber,
    chapter,
    verse,
    morphemeOrdinal: rawTail === 0 ? null : Math.floor(rawTail / 2),
    rawTail,
    tailWasOdd: rawTail % 2 === 1,
  };
}

/**
 * MARBLE book number → our `BookCode`, or null when the book is outside the
 * 66-book backbone. `BOOK_CODES` is already in MARBLE's order, which is why
 * this is an index and not a table.
 */
export function marbleBookToBookCode(bookNumber: number): BookCode | null {
  if (!Number.isInteger(bookNumber) || bookNumber < 1 || bookNumber > BOOK_CODES.length) return null;
  return BOOK_CODES[bookNumber - 1] ?? null;
}

/** Name a book we cannot resolve, for diagnostics. */
export function marbleDeuterocanonName(bookNumber: number): string | null {
  return UBS_FFR_DEUTEROCANON_BOOKS[bookNumber] ?? null;
}

/**
 * Why a reference could not be turned into a backbone anchor. Distinguished
 * because they need different responses: `deuterocanon` is a canon-scope fact
 * about us, `versification` is a real divergence to be fixed with a map, and
 * `malformed` would be a source defect.
 */
export type MarbleResolutionFailure =
  | "malformed"
  | "deuterocanon"
  | "unknown-book"
  | "versification";

export type MarbleResolution =
  | { readonly ok: true; readonly book: BookCode; readonly chapter: number; readonly verse: number; readonly morphemeOrdinal: number | null }
  | { readonly ok: false; readonly reason: MarbleResolutionFailure; readonly bookNumber: number; readonly detail: string };

/**
 * Resolve a decoded reference to a verse the backbone admits.
 *
 * `chapterVerseCounts` is the backbone's `books[code].chapters` array. Passing
 * it in keeps this module free of the loader (INV-18).
 *
 * A reference that names an in-canon book but a verse the backbone lacks is
 * reported as `versification`, NOT as bad data. Every one of the 144 such
 * references in the corpus is a textbook Masoretic-versus-English divergence:
 * Joel 4 (English has 3 chapters), Malachi 3:19–24 (English splits a chapter
 * 4), 1 Kings 5:20 (English 4:21–34 = Hebrew 5:1–14), Exodus 21:37 (English
 * 22:1), Numbers 17:23, Psalm superscriptions counted as verse 1. The
 * references are correct for the Masoretic text; our backbone is numbered the
 * other way. Resolving them needs a versification map, which we do not yet
 * have.
 */
export function resolveMarbleReference(
  ref: MarbleReference,
  chapterVerseCounts: (code: BookCode) => readonly number[] | undefined,
): MarbleResolution {
  const code = marbleBookToBookCode(ref.bookNumber);
  if (!code) {
    const dc = marbleDeuterocanonName(ref.bookNumber);
    return dc
      ? { ok: false, reason: "deuterocanon", bookNumber: ref.bookNumber, detail: dc }
      : { ok: false, reason: "unknown-book", bookNumber: ref.bookNumber, detail: `book ${ref.bookNumber}` };
  }
  const chapters = chapterVerseCounts(code);
  if (!chapters) {
    return { ok: false, reason: "unknown-book", bookNumber: ref.bookNumber, detail: code };
  }
  const maxVerse = chapters[ref.chapter - 1];
  if (ref.chapter < 1 || maxVerse === undefined) {
    return {
      ok: false,
      reason: "versification",
      bookNumber: ref.bookNumber,
      detail: `${code} ${ref.chapter} beyond ${chapters.length} chapters`,
    };
  }
  if (ref.verse < 1 || ref.verse > maxVerse) {
    return {
      ok: false,
      reason: "versification",
      bookNumber: ref.bookNumber,
      detail: `${code} ${ref.chapter}:${ref.verse} beyond ${maxVerse} verses`,
    };
  }
  return { ok: true, book: code, chapter: ref.chapter, verse: ref.verse, morphemeOrdinal: ref.morphemeOrdinal };
}

/** Backbone reference string, matching `toBref` in `src/core/reference`. */
export function marbleToBref(r: Extract<MarbleResolution, { ok: true }>): string {
  return `bref:v1/${r.book}.${r.chapter}.${r.verse}`;
}

// ─────────────────────────────── Copyright ───────────────────────────────────

/**
 * A per-image copyright string, kept verbatim plus whatever structure could be
 * read off it without guessing.
 *
 * `raw` is the contract. `holder`, `source` and `licenseHint` are conveniences
 * for grouping and MUST NOT be used as the displayed credit — the raw string
 * is what the source asserts and the only thing safe to show.
 */
export type UbsFfrCopyright = {
  readonly raw: string;
  /** Best-effort holder with a leading "©" and a trailing source clause removed. */
  readonly holder: string;
  /** e.g. "Wikimedia Commons", "Pixabay", when the string names one. */
  readonly source: string | null;
  /** A CC/PD token found in the string, verbatim, e.g. "CC BY-SA 3.0", "CC0". */
  readonly licenseHint: string | null;
  /** True when the string names no attributable holder at all. */
  readonly unattributable: boolean;
  /** True when the string says the image is model-generated. */
  readonly machineGenerated: boolean;
};

const SOURCE_PATTERNS: ReadonlyArray<readonly [RegExp, string]> = [
  // "Wikimedia Coomons" / "Wikimedia Common" are upstream typos; match them.
  [/Wikimedia\s+Comm?o?n?s?/i, "Wikimedia Commons"],
  [/Wikiedia\s+Commons/i, "Wikimedia Commons"],
  [/Pixabay/i, "Pixabay"],
  [/Metropolitan\s+Museum\s+of\s+Art/i, "Metropolitan Museum of Art"],
  [/Israel\s+Government\s+Press\s+Office/i, "Israel Government Press Office"],
  [/British\s+Museum/i, "British Museum"],
  [/Library\s+of\s+Congress/i, "Library of Congress"],
  [/archive\.org/i, "archive.org"],
  [/Flickr/i, "Flickr"],
  [/USDA/i, "USDA"],
];

const LICENSE_HINT_RE =
  /\bCC0\b|\bCC\s+BY(?:-SA)?(?:\s+\d(?:\.\d)?)?(?:\s+[A-Z]{2})?\b|\bPublic\s+domain\b/i;

const UNATTRIBUTABLE_RE = /^\(?\s*source\s+unknown\s*\)?$/i;

const MACHINE_RE = /\bChatGPT\b|\bOpenAI\b|\bDALL[-·\s]?E\b|\bMidjourney\b/i;

/**
 * Structure a copyright string without losing it.
 *
 * Deliberately conservative. Ray Pritz alone appears as "Ray Pritz (UBS)",
 * "© Ray Pritz (UBS)", "© Ray Pritz by United Bible Societies" and
 * "© Ray Pritz (UBS" (an unclosed parenthesis upstream). Normalising those to
 * one holder is useful for a count and *wrong* as a credit, so both forms are
 * returned and the caller decides.
 */
export function parseImageCopyright(rawInput: string): UbsFfrCopyright {
  const raw = rawInput.trim();
  if (raw === "") {
    return { raw, holder: "", source: null, licenseHint: null, unattributable: true, machineGenerated: false };
  }
  if (UNATTRIBUTABLE_RE.test(raw)) {
    return { raw, holder: raw, source: null, licenseHint: null, unattributable: true, machineGenerated: false };
  }

  let source: string | null = null;
  for (const [re, name] of SOURCE_PATTERNS) {
    if (re.test(raw)) {
      source = name;
      break;
    }
  }
  const licenseMatch = LICENSE_HINT_RE.exec(raw);
  const licenseHint = licenseMatch ? licenseMatch[0].replace(/\s+/g, " ") : null;

  // Holder: drop a leading ©, then cut at the first clause that is plainly a
  // source or licence rather than a name.
  let holder = raw.replace(/^\s*©\s*/, "");
  const cut = holder.search(
    /\s*(?:\(|,\s*(?:CC0|CC\s+BY|Public\s+domain|via\b)|\s+via\b|\s*-\s*Wikimedia|\s*©\s*Wikimedia|\s+by\s+United\s+Bible\s+Societies)/i,
  );
  if (cut > 0) holder = holder.slice(0, cut);
  holder = holder.replace(/\s+/g, " ").trim();

  return {
    raw,
    holder,
    source,
    licenseHint,
    unattributable: holder === "",
    machineGenerated: MACHINE_RE.test(raw),
  };
}

// ───────────────────────────────── Entities ──────────────────────────────────

/**
 * One plate. `fileName` + `collection` identify it; `path` is absent on
 * purpose — see note 1 in the file header. `bytes` are not shipped.
 */
export type UbsFfrImage = {
  readonly id: string;
  readonly handbook: UbsFfrHandbook;
  readonly fileName: string;
  readonly collection: string;
  readonly caption: string;
  readonly copyright: UbsFfrCopyright;
  /** `ILL` in FLORA/FAUNA; absent on 391 of REALIA's 392 images. */
  readonly type: string | null;
  readonly description: string | null;
};

/** One language set: a lemma in one language plus every place it occurs. */
export type UbsFfrLanguageSet = {
  readonly language: string;
  readonly lemma: string;
  readonly transliteration: string | null;
  readonly references: readonly MarbleReference[];
};

/** One handbook entry, e.g. FLORA 1.16 "Oak". */
export type UbsFfrEntry = {
  readonly key: string;
  readonly handbook: UbsFfrHandbook;
  readonly title: string;
  readonly languageSets: readonly UbsFfrLanguageSet[];
  readonly images: readonly UbsFfrImage[];
};

/**
 * Anchor candidate: one lemma occurrence, resolved as far as it can be.
 *
 * ── Why this is not yet a backbone-token anchor ────────────────────────────
 * Our annotation anchors are `{verse, position}` over `backbone-token:v1`,
 * whose own meta declares `position_unit: "1-based-source-slot-within-verse"`,
 * `position_basis: non-empty original-language rows sorted by Heb/Greek Sort`,
 * `cross_corpus_position_equivalence: "none"` and
 * `not_equivalent_to: ["MACULA","OSHB"]`.
 *
 * A MARBLE ordinal is *morpheme*-level in MARBLE's segmentation. So it is
 * finer than a backbone-token slot AND counted on a different basis. Turning
 * one into the other needs two steps we have not built: coarsen morpheme →
 * word, then remap that word across corpora. `morphemeOrdinal` is therefore
 * carried through verbatim and NOT written into a `position` field, so that
 * nothing downstream can mistake it for one. Verse-level attachment is exact
 * today; word-level attachment is a further piece of work.
 */
export type UbsFfrAnchor = {
  readonly handbook: UbsFfrHandbook;
  readonly entryKey: string;
  readonly title: string;
  readonly language: string;
  readonly lemma: string;
  readonly bref: string;
  readonly morphemeOrdinal: number | null;
  readonly corpus: UbsFfrCorpus | null;
};

/** Non-throwing text of an element's descendants, with tags flattened. */
export function flattenXmlText(fragment: string): string {
  return fragment
    .replace(/<[^>]*>/g, "")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Split a lemma field into its alternatives. Several are comma-separated pairs
 * — "אֵלָה, אַלָּה", "אֹהֶל, מוֹעֵד" — and a join wants each half.
 */
export function splitLemmaAlternatives(lemma: string): readonly string[] {
  return lemma
    .split(/[,;]/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);
}

/** Strip Hebrew points and cantillation, and unify final forms, for joining. */
export function hebrewConsonantalSkeleton(input: string): string {
  const FINALS: Readonly<Record<string, string>> = {
    "ך": "כ", // ך → כ
    "ם": "מ", // ם → מ
    "ן": "נ", // ן → נ
    "ף": "פ", // ף → פ
    "ץ": "צ", // ץ → צ
  };
  let out = "";
  for (const ch of input.normalize("NFD")) {
    if (ch >= "א" && ch <= "ת") out += FINALS[ch] ?? ch;
  }
  return out;
}

/** Strip Greek diacritics and case-fold, for joining against MACULA lemmas. */
export function greekLemmaSkeleton(input: string): string {
  // Escapes, not literal combining marks: a literal U+0300-block character in
  // source is invisible and does not survive casual copy/paste editing.
  return input
    .normalize("NFD")
    .replace(/[\u0300-\u036f\u1fbd-\u1fff\u0374\u0375]/g, "")
    .toLowerCase()
    .trim();
}

/** Shape of the emitted index file. */
export type UbsFfrIndex = {
  readonly version: 1;
  readonly source: string;
  readonly license: string;
  readonly licenseUrl: string;
  readonly licenseRiders: readonly string[];
  readonly attribution: Readonly<Record<string, string>>;
  readonly generatedAt: string;
  readonly sourceSha256: Readonly<Record<string, string>>;
  readonly counts: Readonly<Record<string, number>>;
  readonly entries: readonly UbsFfrEntry[];
};
