// Vendors the Quire faces from Google Fonts into src/renderer/fonts/ and
// regenerates src/renderer/fonts.css.
//
// Why vendored: this is a local-first reader. Fetching the brand faces from
// fonts.gstatic.com at runtime means an offline launch silently falls back to
// Georgia and system-ui, which is exactly the failure the type study is trying
// to prevent.
//
// Why Greek and Hebrew are aliased into the reading family rather than appended
// to --font-reading's stack: Source Serif 4 carries monotonic Greek (α, ρ, χ)
// but NOT polytonic (ἀ, ῇ, ᾶ), and no Hebrew at all. A plain fallback stack
// would therefore set `ἐν ἀρχῇ` half in Source Serif and half in the fallback,
// mid-word. Declaring the Greek and Hebrew faces under the SAME family name
// with an explicit unicode-range — after the Latin faces, so they win the
// overlap — routes every Greek and Hebrew codepoint to one consistent face.
//
//   node scripts/vendor-fonts.mjs
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36";
const ROOT = new URL("../src/renderer/", import.meta.url).pathname;
const FONT_DIR = `${ROOT}fonts`;

// Order matters: later @font-face rules win an overlapping unicode-range, so
// the Greek and Hebrew overrides must follow the Latin faces they override.
const FAMILIES = [
  {
    slug: "source-serif-4",
    query: "Source+Serif+4:ital,opsz,wght@0,8..60,300..700;1,8..60,300..700",
    subsets: ["latin", "latin-ext"],
    note: "Reading face — scripture, notes, definitions, entry content.",
  },
  {
    slug: "instrument-sans",
    query: "Instrument+Sans:ital,wdth,wght@0,75..100,400..700;1,75..100,400..700",
    subsets: ["latin", "latin-ext"],
    note: "UI face — labels, references, actions, dates, tabs.",
  },
  {
    slug: "geist-mono",
    query: "Geist+Mono:wght@100..900",
    subsets: ["latin", "latin-ext"],
    note: "Chrome instrumentation — register, header, shortcuts, metadata.",
  },
  {
    slug: "noto-serif-greek",
    query: "Noto+Serif:ital,wght@0,300..700;1,300..700",
    subsets: ["greek", "greek-ext"],
    aliasTo: "Source Serif 4",
    note:
      "Greek, aliased into the reading family. Source Serif 4 stops at\n   monotonic; greek-ext (U+1F00-1FFF) is where every breathing, circumflex\n   and iota subscript in the Greek New Testament lives.",
  },
  {
    slug: "noto-serif-hebrew",
    query: "Noto+Serif+Hebrew:wght@300..700",
    subsets: ["hebrew"],
    aliasTo: "Source Serif 4",
    note:
      "Hebrew, aliased into the reading family. Carries the niqqud — many\n   system serifs render the consonants and drop the pointing silently.",
  },
];

await rm(FONT_DIR, { recursive: true, force: true });
await mkdir(FONT_DIR, { recursive: true });

const blocks = [];

for (const family of FAMILIES) {
  const res = await fetch(
    `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`,
    { headers: { "User-Agent": UA } },
  );
  if (!res.ok) throw new Error(`${family.slug}: CSS fetch failed ${res.status}`);

  // Google emits `/* subset */` then one @font-face per subset. Split on the
  // labels so we can keep only the subsets this app actually sets type in.
  const chunks = (await res.text()).split(/\/\*\s*([a-z0-9-]+)\s*\*\/\n/i);
  const kept = [];
  let index = 0;

  for (let i = 1; i < chunks.length; i += 2) {
    const subset = chunks[i];
    if (!family.subsets.includes(subset)) continue;

    let face = chunks[i + 1].trim();
    const remote = face.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/);
    if (!remote) throw new Error(`${family.slug}/${subset}: no woff2 url`);

    const style = /font-style:\s*italic/.test(face) ? "italic" : "roman";
    const name = `${family.slug}-${subset}-${style}-${index++}.woff2`;
    const bin = await fetch(remote[1], { headers: { "User-Agent": UA } });
    if (!bin.ok) throw new Error(`${name}: ${bin.status}`);
    await writeFile(`${FONT_DIR}/${name}`, Buffer.from(await bin.arrayBuffer()));

    face = face.replace(remote[1], `./fonts/${name}`);
    if (family.aliasTo) {
      face = face.replace(/font-family:\s*'[^']+'/, `font-family: '${family.aliasTo}'`);
    }
    kept.push(`/* ${subset} */\n${face}`);
  }

  if (!kept.length) throw new Error(`${family.slug}: no subsets matched`);
  blocks.push(`/* ${family.slug} — ${family.note} */\n${kept.join("\n")}`);
  console.log(`${family.slug}: ${kept.length} faces`);
}

const header = `/* Quire faces, vendored so the app renders identically offline.
   Generated by scripts/vendor-fonts.mjs — edit that, not this.

   Three voices (handoff §4): Source Serif 4 for anything you read, Instrument
   Sans for UI, Geist Mono for chrome instrumentation.

   The last two blocks are not a fourth and fifth voice. They are Greek and
   Hebrew declared UNDER the reading family's own name with an explicit
   unicode-range, so those scripts resolve to one face instead of being split
   glyph-by-glyph between Source Serif 4 and whatever the OS offers. */
`;

await writeFile(`${ROOT}fonts.css`, `${header}\n${blocks.join("\n\n")}\n`);

const files = await readdir(FONT_DIR);
console.log(`\n${files.length} woff2 files in src/renderer/fonts/`);
